### ISSUE TITLE
Initial loading speed is very slow

### ISSUE THREAD

**Issue by javier3434** [sambecker/exif-photo-blog#100]
Hi, sambencker ,thanks for your great work!
But I dtk why this nextjs project's initial loading has specific slow speed.(every route, even pages without images)
I run the codes locally and my database is cloudflare blob+ vercel postgres.
I tried to analyze and improve it but i failed. 
I do not know if you have the same phenomenon, I have here the white screen obviously perceptible wait, (around 2-3 seconds even longer)  and thanks for any suggestions.

![Snipaste_2024-05-31_11-54-53](https://github.com/sambecker/exif-photo-blog/assets/52641452/fcba9884-87b4-4d73-9f91-d2c361ae6f8c)

![Snipaste_2024-05-31_11-55-28](https://github.com/sambecker/exif-photo-blog/assets/52641452/36455718-c208-4da6-b438-e3aa92400e2d)

**Comment by sambecker** [comment]
Yeah, that doesn't sound right. At a minimum, the core pages `/` and `/grid` should be statically rendered ahead of time.

I'm always tweaking performance, and have implemented the following:
- Loading auth on client after initial load
- Disabling middleware on core pages: `/` and `/grid`
- Statically generating photos (this can be enabled by configuring):
  - `NEXT_PUBLIC_STATICALLY_OPTIMIZE_PAGES = 1` and
  - `NEXT_PUBLIC_STATICALLY_OPTIMIZE_OG_IMAGES = 1`

I plan to ship `PPR` once that's stable enough.

A few questions:
- Are you experiencing this in production or locally?
- If production, do you have a hosted link I could inspect?
- Are you using the latest code?
- Have you customized the code in any way?

**Comment by sambecker** [comment]
> I run the codes locally

Just realized you mentioned that this is happening locally.

Only thing I can think of to speed up local development is to try `turbopack` by running:
```
vercel env pull
pnpm dev --turbo
```

If you sync your fork now, you won't need the `--turbo` which I've just added to the template.

Closing this for now.

**Comment by javier3434** [comment]
i will try it ,thanks a lot!
