### ISSUE TITLE
encountered errors when build project

### ISSUE THREAD

**Issue by javier3434** [sambecker/exif-photo-blog#102]
Hi, Sambecker
**Describe the bug**
I can run this project correctly. but when i try "pnpm run build",there is an error as below.

i tried build it on commit branch like before 19/05 or some earlier commit branches.it succeed.

**Does your template use custom code?**
No, i cloned a new project ,but encountered same error.

**Steps to Reproduce**
1.clone this project main branch
2.Setup Auth and .env ( i use cloudflare blob+ vercel postgres)
3.pnpm install and pnpm run build

**Screenshots**

![Snipaste_2024-06-04_16-00-14](https://github.com/sambecker/exif-photo-blog/assets/52641452/91ac73b1-11ae-4619-ab10-21082b9b6b55)
![Snipaste_2024-06-04_16-00-29](https://github.com/sambecker/exif-photo-blog/assets/52641452/fdd53698-824f-4d2b-87d9-7198b1eba4a2)
Error occurred prerendering page "/template-image-tight".
Error occurred prerendering page "/template-image-tight".
Error occurred prerendering page "/home-image".

**Environment details**
node version:20.11.0
pnpm version:8.15.7

**Comment by sambecker** [comment]
Do you have `NEXT_PUBLIC_SITE_DOMAIN` set, and is it available locally?

**Comment by javier3434** [comment]
thank you, that's the reason
