### ISSUE TITLE
Mass Apply Tags

### ISSUE THREAD

**Issue by EmilianoGarciaLopez** [sambecker/exif-photo-blog#104]
Be able to select multiple photos and apply the same tag to them, like the current batch-upload modal

**Comment by sambecker** [comment]
This is a really nice idea and something I've been planning to work on for a while.

Basically, a multi-select interface allowing batch actions to:
- Hide
- Favorite
- Delete
- Apply tags

Will keep you posted!

**Comment by sambecker** [comment]
Just merged! cc @EmilianoGarciaLopez @bg1ttr
