### ISSUE TITLE
AI cannot generate names properly when multiple photos are uploaded at once

### ISSUE THREAD

**Issue by huhuhang** [sambecker/exif-photo-blog#108]
**Describe the bug**

AI cannot generate names properly when multiple photos are uploaded at once.

**Does your template use custom code?**
If so, what features/customizations have you added?

**Steps to Reproduce**

**Screenshots**

![20240612-11-02-32-917xq1l8](https://github.com/sambecker/exif-photo-blog/assets/5147530/ec1a840b-9381-41dc-970f-44307355e30a)
![20240612-11-03-07-C7E9F6s7](https://github.com/sambecker/exif-photo-blog/assets/5147530/160c6b94-91c6-4080-baa6-148c27803301)

**Device details**
 - Device/OS: [e.g. Windows, macOS, iPhone15Pro, Android]

**Comment by sambecker** [comment]
Can reproduce. Just posted a small fix. Can you sync your fork and try again?

**Comment by sambecker** [comment]
Closing for now! LMK if you experience this issue again.
