### ISSUE TITLE
Caption placeholder missing

### ISSUE THREAD

**Issue by solomonshalom** [sambecker/exif-photo-blog#112]
Hi!

When a mate of mine uploaded an image to the photo-blog, there was an option to add caption but the images that he uploaded after the initial image, didn't give him an option to write a caption for it

I didn't change the codebase, all I did was add the ENVs and had placed the production domain to it.

I am not so sure why this happened 🤔

**Comment by ctrl-beep** [comment]
Yep! Same here

The first Image had the option:
![image](https://github.com/sambecker/exif-photo-blog/assets/172896165/a9b66041-952e-49af-9572-850c7c26d7c5)

Second didn't:
![image](https://github.com/sambecker/exif-photo-blog/assets/172896165/3056c76a-afbf-4899-a30d-7c9a6e837950)

Not so sure on what to do 😬

**Comment by sambecker** [comment]
@solomonshalom @ctrl-beep the Caption field should show up once you've added Title text. This was done to avoid overwhelming new users. Can you confirm it works that way? Open to revisiting if that's confusing.

**Comment by solomonshalom** [comment]
> @solomonshalom @ctrl-beep the Caption field should show up once you've added Title text. This was done to avoid overwhelming new users. Can you confirm it works that way? Open to revisiting if that's confusing.

OH! I tried and it worked!

I didn't know that, thank you 😭
