### ISSUE TITLE
Can we have the Grid view as the default?

### ISSUE THREAD

**Issue by solomonshalom** [sambecker/exif-photo-blog#113]
Hi! @sambecker,

Hope you're doing great!

I had a small Q: is it possible to have the grid view as the default when people open up the page?

Would love to know!

**Comment by sambecker** [comment]
Definitely something I've considered—will size this one up. Should't be too hard to do.

**Comment by solomonshalom** [comment]
> Definitely something I've considered—will size this one up. Should't be too hard to do.

Alright! Pretty excited to see how you do it!

**Comment by sambecker** [comment]
Of course, this one turned into a giant PR 🤦‍♂️

Just merged #120 which exposes `NEXT_PUBLIC_GRID_HOMEPAGE`

Let me know if it works as expected

**Comment by solomonshalom** [comment]
> Of course, this one turned into a giant PR 🤦‍♂️
> 
> Just merged #120 which exposes `NEXT_PUBLIC_GRID_HOMEPAGE`
> 
> Let me know if it works as expected

Oh my! Thanks @sambecker :D
