### ISSUE TITLE
Vertical Images

### ISSUE THREAD

**Issue by amgno** [sambecker/exif-photo-blog#114]
Hey so I just found out about this project after spending two full days building mine. What a shame.
Only thing that kind of bothers me it the fact that you can't fully view a vertical image, since you need to scroll. 
Would you mind adding a way or simply resize the image to the current viewport?

Except this I really love the project, keep it up!

**Comment by sambecker** [comment]
The way to achieve this currently @amgno is by setting `NEXT_PUBLIC_MATTE_PHOTOS=1`—feedback welcome!
