### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by XahidEx** [sambecker/exif-photo-blog#12]
Do you have any thoughts on replacing Vercel blob? Because Vercel free plan has a 100 MB data-transfer (monthly) limit for Blob.
There can be an alternative as well.

**Comment by sambecker** [comment]
Not yet, but it's definitely something we're thinking about.

Do you have a preference on which blob service you would like to use?

**Comment by narwhrl** [comment]
> Not yet, but it's definitely something we're thinking about.
> 
> Do you have a preference on which blob service you would like to use?

I thought [Cloudflare R2](https://developers.cloudflare.com/r2/) could be a good choice.
It has 10GB free storage and no charges for egress bandwidth.

**Comment by sambecker** [comment]
#21 adds support for [AWS S3](https://github.com/sambecker/exif-photo-blog#aws-s3)
