### ISSUE TITLE
The AI ​​function configuration is wrong, but I used the correct API Key

### ISSUE THREAD

**Issue by bg1ttr** [sambecker/exif-photo-blog#121]
“OpenAI connection error: "The model `gpt-4o` does not exist or you do not have access to it."

This is the error message I received. I configured the user API through the open ai background. I confirmed that the API was copied correctly and completed the environment configuration and redeployment through vercel.

<img width="1504" alt="截屏2024-07-04 19 59 49" src="https://github.com/sambecker/exif-photo-blog/assets/11238817/d1dfb6dd-9b8d-4f86-98ab-919a700a2380">
<img width="605" alt="截屏2024-07-04 19 59 54" src="https://github.com/sambecker/exif-photo-blog/assets/11238817/7349e125-e075-4fb6-a445-4b93e7b0bfc0">
<img width="1390" alt="截屏2024-07-04 20 00 16" src="https://github.com/sambecker/exif-photo-blog/assets/11238817/c72cdef9-5a4e-4d45-9d67-8b279112ad52">

**Comment by bg1ttr** [comment]
I found an explanation about this issue
https://github.com/sambecker/exif-photo-blog/issues/110

**Comment by sambecker** [comment]
Yeah, can't say I've run into this issue but we've heard from folks that they needed to pre-pay in order to use the API.

Hope you were able to make it work!
