### ISSUE TITLE
About FILMS Function

### ISSUE THREAD

**Issue by bg1ttr** [sambecker/exif-photo-blog#122]
Hello, first of all, thank you for your excellent work. I can't find the configuration path and introduction regarding the FILMS function in your sample website(https://photos.sambecker.com/film/acros). Can you briefly introduce the function and how to use this function? From your sample website, it looks more like an independent album collection. But I can't find any entry to set this function in the website settings.

Best regards,
bg1ttr

<img width="160" alt="截屏2024-07-04 21 29 05" src="https://github.com/sambecker/exif-photo-blog/assets/11238817/ccfc717c-9ed7-486e-ae30-14298f891b76">
<img width="1025" alt="截屏2024-07-04 21 31 36" src="https://github.com/sambecker/exif-photo-blog/assets/11238817/970a026a-b81b-4c63-a5c1-610232840862">

**Comment by sambecker** [comment]
Yes! [Film simulations](https://fujifilm-x.com/en-us/exposure-center/get-to-grips-with-film-simulation-modes/) are a feature of Fuji cameras. You when upload a photo shot on a Fuji camera we will surface the film simulation mode used, and place that film in the grid sidebar.
