### ISSUE TITLE
Custom grid size / amount of photos per row

### ISSUE THREAD

**Issue by vhogberg** [sambecker/exif-photo-blog#125]
Hello!
Would it be possible to be able to adjust the grid size so that photos in the grid are bigger (i.e less photos on each row).
Now what I can see it is either 6, 4 or 2 photos per row depending on screen size.

I like the sweet spot that Instagram for example has of 3 photos per row. Personally having 4 per row which becomes the default for most phones (as far as I've tested) is too small, and I think 3, or even 2, would look better. Same goes for whilst on PC in landscape, I think having 6 photos on a row makes them too small.

And this only goes for when the photos are square in the grid I guess. Because https://photos.sambecker.com/grid for example looks great, but I guess that is because all photos are in landscape and have the same aspect ratio.

Just a thought, love everything about your template otherwise <3

**Comment by sambecker** [comment]
Definitely open to this idea, though I'd want it to align with the site grid. That's why 1:1 photos are 4-across and 3:2 photos are 2-across. We could offer 2-across on square photos, it's just that they get quite large.

Will think on a potential compromise. Offering one of these paths via configuration feels reasonable.

**Comment by sambecker** [comment]
Just [added configuration](https://github.com/sambecker/exif-photo-blog/commit/bbc1626e7be3d087c1ae3926e40911e278d85654) for increasing the amount of grid photos per row via `NEXT_PUBLIC_SHOW_LARGE_THUMBNAILS`. Hopefully this works as desired!

**Comment by vhogberg** [comment]
Tested a bit and looks really good to me.
Tysm again!

**Comment by sambecker** [comment]
Of course!
