### ISSUE TITLE
how about adding support for  payloadcms 3 ?

### ISSUE THREAD

**Issue by santoshgistto** [sambecker/exif-photo-blog#126]
**Is your feature request related to a problem? Please describe.**

-   Granular access 
- User management 

**Describe the solution you'd like**
I would like other visiting user can also upload the images

**Comment by sambecker** [comment]
Hi @santoshgistto at the time current time, multi-user collaboration is beyond the scope of this template. You could always share a login account between admins or tweak the template to accept multiple sets of credentials.
