### ISSUE TITLE
Homepage text

### ISSUE THREAD

**Issue by ghenry** [sambecker/exif-photo-blog#127]
Hi,

Is there any where to set a bit of text, like the About section of a github repo?

Thank.s

**Comment by sambecker** [comment]
Any sense for how long this text would be, and whether or not you'd expect to see it on every page?

**Comment by ghenry** [comment]
Probably 150 I think, looking at some of my github repos.

**Comment by sambecker** [comment]
Working on this on #129—should be able to merge later today

**Comment by sambecker** [comment]
Merged!
