### ISSUE TITLE
is there a way to show more merits for Hasselblad's photo?

### ISSUE THREAD

**Issue by cigar** [sambecker/exif-photo-blog#131]
@sambecker Thanks for keeping this repo up to date. I love this excellent repo and am so glad I can use it to show my photo; so far, everything is lovely.
There is one thing I request: How can I show my [Hasselblad](https://lens.cigar.design/p/1rXS0kVI) photo's merits for each photo as you did on your website:
- [90mm] 135mm
- ƒ/2
- 1/3499s
- ISO 125
- 0ev

So far, I haven't seen IOS, and the aperture, I only have the following merits:
- [43mm]
- 1/25s
- 0ev
- 23 MAY 2024 8:39PM

**Comment by sambecker** [comment]
Hi @cigar—will examine those files. Not sure what's going on there. Also noticed that blur wasn't being generated correctly for some of your photos so I pushed a quick compatibility fix for that!

**Comment by sambecker** [comment]
Examined one of your files and it looks like there's not a ton of EXIF data there, not sure why.

I was able to introduce aperture and ISO compatibility improvements in a [small update](https://github.com/sambecker/exif-photo-blog/commit/4c092cef54cbeb6c340eb41cfb1d72ada5616bbd), so try updating your fork and either add a new file or sync an existing file to see if more data comes in!
