### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by jbgolds** [sambecker/exif-photo-blog#132]
Hey Sam, thanks for all your hard work creating this. Has reopened my eyes to photography!!

I have done some work in a private repo fork of this project to dockerize + self host the app. It's a bit "hacky" as of right now: 

- Regarding self hosting images, can run a local https://min.io server to act as buckets, but it seems the S3 API <> Minio Server are not fully compatible, specifically the pre-signing of URLs. 
   - For the time being to get around this, I've just used Cloudflare R2 as 10GB free is pretty sweet :). I can build out the APIs to properly interact with a Minio Docker Container, but have tabled that for awhile as 10GB storage and cloudflare caching keeps R2 operation rates super low. 
- I'm using cloudflare tunnels to open the service to internet without exposing ports for ease + for those who have dynamic IPs. This leaves my VPS's only open port to be the SSH port. 
- Regarding your previous comment about another issue with `next/image`, I run my own[ image optimization server ](https://github.com/coollabsio/next-image-transformation)and use a custom loader to instead hit that server. 
- Regarding the "hacky" part, I'm having issues getting it to build off a single `docker compose up` due to DB connection problems during BUILD time only. Usually end up having to build Postgres container first, and then building the nextjs app. I believe this can be solved with actually publishing a docker image. 
- Image share rendering does not seem to work like it does on Vercel, will need to dig into this but not my biggest concern. 

I have moved this over and am hosting this on a VPS using ~1GB of RAM for everything, happy to share url over email for you to take a look as not ready to post publicly incase of any security issue I may have overlooked 😅.

**Comment by sambecker** [comment]
Amazing! Will direct people to this post if they're looking to self-host. Can't wait to see the end product.

**Comment by hmfaysal** [comment]
This comment inspired me to create clients and components that enable the project to be fully locally hosted. Initially, I attempted to use local file system-based storage, but the next/image component did not interact well with local routes. Therefore, I eventually transitioned to Minio, and using Minio with a slightly modified AWS S3 client proved to be a successful solution.

Regarding the database, I opted for Postgres 16. For the AI component, I used Llama:7b with ollama.

I want to express my gratitude for this fantastic project.

Here’s the live project: https://fays.al/

**Comment by hmfaysal** [comment]
> May I ask if your project will be open-sourced?

Of course, I’ll open a PR once I’ve ironed out some of the kinks I introduced while tinkering with this code base. I need to allocate another weekend for this task.

**Comment by dvlin-dev** [comment]
> > May I ask if your project will be open-sourced?
> 
> Of course, I’ll open a PR once I’ve ironed out some of the kinks I introduced while tinkering with this code base. I need to allocate another weekend for this task.

I can't wait to show my photos, thank you for your efforts.

**Comment by dbolger** [comment]
Another issue to point out with my self-hosted version is that the redirect after logging in seems to be broken. It looks like it's trying to point to some hash (I think the container hash) in the redirect after successfully signing in:
`https://7cffe46d3092:3000/admin/photos`.

**Comment by amlkiller** [comment]
> Another issue to point out with my self-hosted version is that the redirect after logging in seems to be broken. It looks like it's trying to point to some hash (I think the container hash) in the redirect after successfully signing in:我自托管版本需要指出的另一个问题是，登录后的重定向似乎已损坏。看起来它在成功登录后的重定向中试图指向某个哈希（我认为是容器哈希）： `https://7cffe46d3092:3000/admin/photos`.
> 
> Edit: Yep, this is the case:编辑：是的，情况就是这样：
> 
> ```
> docker container ls | grep 7cffe46d3092
> 7cffe46d3092   exif-photo-blog                                           "docker-entrypoint.s…"   2 days ago     Up 2 days                    0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp
> ```

Hello, I have a question.
RustFS is a competitor to MinIO, written in Rust. Is it compatible with the S3 API of your project?
Attached is the project link: https://github.com/rustfs/rustfs

**Comment by dbolger** [comment]
> > Another issue to point out with my self-hosted version is that the redirect after logging in seems to be broken. It looks like it's trying to point to some hash (I think the container hash) in the redirect after successfully signing in:我自托管版本需要指出的另一个问题是，登录后的重定向似乎已损坏。看起来它在成功登录后的重定向中试图指向某个哈希（我认为是容器哈希）： `https://7cffe46d3092:3000/admin/photos`.
> > 
> > Edit: Yep, this is the case:编辑：是的，情况就是这样：
> > 
> > ```
> > docker container ls | grep 7cffe46d3092
> > 7cffe46d3092   exif-photo-blog                                           "docker-entrypoint.s…"   2 days ago     Up 2 days                    0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp
> > ```
> 
> Hello, I have a question.
> RustFS is a competitor to MinIO, written in Rust. Is it compatible with the S3 API of your project?
> Attached is the project link: https://github.com/rustfs/rustfs

I have no idea. If RustFS operates on the same S3 API as MinIO I don't see why it wouldn't work. You should try it and see.

**Comment by amlkiller** [comment]
> > > Another issue to point out with my self-hosted version is that the redirect after logging in seems to be broken. It looks like it's trying to point to some hash (I think the container hash) in the redirect after successfully signing in:我自托管版本需要指出的另一个问题是，登录后的重定向似乎已损坏。看起来它在成功登录后的重定向中试图指向某个哈希（我认为是容器哈希）： `https://7cffe46d3092:3000/admin/photos`.
> > > Edit: Yep, this is the case:编辑：是的，情况就是这样：
> > > ```
> > > docker container ls | grep 7cffe46d3092
> > > 7cffe46d3092   exif-photo-blog                                           "docker-entrypoint.s…"   2 days ago     Up 2 days                    0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp
> > > ```
> > 
> > 
> > Hello, I have a question.
> > RustFS is a competitor to MinIO, written in Rust. Is it compatible with the S3 API of your project?
> > Attached is the project link: https://github.com/rustfs/rustfs
> 
> I have no idea. If RustFS operates on the same S3 API as MinIO I don't see why it wouldn't work. You should try it and see.

ok I will try it.

**Comment by LostXine** [comment]
Thanks to everyone in this thread for sharing your solutions. After going through the previous posts and checking the latest codebase, I’ve put together a beginner-friendly guide that sums everything up. However, I have very limited knowledge in this domain, so please feel free to correct me.

## Step 0 — What you’ll set up

This guide spins up several Dockerized services required for the project and the project itself:

Service | Purpose | Default Port(s) | Direct User Access?
-- | -- | -- | --
MinIO | Object/image storage (S3-compatible) | 9000 (API), 9001 (optional Console/WebUI) | Yes (API). Console optional.
PostgreSQL | Image metadata database | 5432  (local only) | Yes for your app and the machine to build the Docker image. No, for general users.
coollabsio/next-image-transformation | Image optimization wrapper | 8999 | Yes
imgproxy | Core image transformation engine | 8080 (local only) | No (used behind the wrapper)
This project (app) | Main web application | 3000 | Yes

***Important security note***
> Several services will be reachable over the network. Do not use this configuration as-is for production. In my case, I use Nginx as a reverse proxy route by requested URLs to each container.

## Step 1: Clone the project and create the following files in the root directory of the project.

The following two edits are borrowed from [coollabsio/next-image-transformation](https://github.com/coollabsio/next-image-transformation)

<details>
<summary>Add the following lines to the end of <b>next.config.ts</b></summary>

```ts
module.exports = {
  images: {
    loader: 'custom',
    loaderFile: './loader.js',
  },
}
```
</details>

<details>
<summary>Create a new file named <b>loader.js</b>, change <i>imageOptimizationApi</i> to your coollabsio/next-image-transformation container, and change <i>baseUrl</i> to your exif-photo-blog (this repo) container</summary>

```js
'use client'

export default function myImageLoader({ src, width, quality }) {
    const isLocal = !src.startsWith('http');
    const query = new URLSearchParams();

    const imageOptimizationApi = '{change this to next-image-transformation container}';
    // Your NextJS application URL
    const baseUrl = '{change this to exif-photo-blog container}';

    const fullSrc = `${baseUrl}${src}`;

    if (width) query.set('width', width);
    if (quality) query.set('quality', quality);

    if (isLocal && process.env.NODE_ENV === 'development') {
        return src;
    }
    if (isLocal) {
        return `${imageOptimizationApi}/image/${fullSrc}?${query.toString()}`;
    }
    return `${imageOptimizationApi}/image/${src}?${query.toString()}`;
}
```
</details>


<details>
<summary> Create <b>Dockerfile</b> - this code was generated by GPT5 and I'm not able to review it - please correct it if you found anything wrong </summary>

```
# ---------- deps ----------
FROM node:18-alpine AS deps
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# ---------- builder ----------
FROM node:18-alpine AS builder
WORKDIR /app
RUN corepack enable
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm build

# Helpful: show what got built (debug once; remove later)
RUN ls -la .next && ls -la .next/static || true

# ---------- runner (non-standalone) ----------
FROM node:18-alpine AS production
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN corepack enable

# Install only prod deps to run `next start`
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

# Copy build artifacts and public assets
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["pnpm", "exec", "next", "start", "-p", "3000"]
```
</details>

<details>
<summary> <b>other-docker-compose.yaml</b> for all the containers except this repo. Edit where do you what to put images and the db - look for {edit me} </summary>

```
services:
  epb-img-transform-api:
    image: ghcr.io/coollabsio/next-image-transformation:latest
    environment:
      NODE_ENV: production
      ALLOWED_REMOTE_DOMAINS: "*"
      IMGPROXY_URL: http://epb-imgproxy:8080
    depends_on:
      epb-imgproxy:
        condition: service_healthy
    ports:
      - "8999:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  epb-imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      IMGPROXY_AUTO_WEBP: "false"
      IMGPROXY_JPEG_PROGRESSIVE: "true"
      IMGPROXY_USE_ETAG: "true"
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    env_file: [.env]
    command: server /data
    volumes:
      - {edit me - this is your minio storage}:/data
    ports:
      - "9000:9000"   # S3 API
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  epb-postgres:
    image: postgres:16-alpine
    env_file: [.env]
    volumes:
      - {edit me - this is your postgres storage}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    restart: unless-stopped

```
</details>

<details>
<summary> <b>docker-compose.yaml</b></summary>

```
services:
  exif-photo-blog:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    ports:
      - "3000:3000"     # publish the app
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
```
</details>

<details>
<summary><b>.env</b> - Edit the environment variables here. For some variables, you’ll need to rebuild the Docker image for the changes to take effect.</summary>

```
# ---- App admin/auth ----
AUTH_SECRET={Required by this project}
ADMIN_EMAIL={Required by this project}
ADMIN_PASSWORD={Required by this project}

# ---- Postgres ----
POSTGRES_USER={your postgres username}
POSTGRES_PASSWORD={your postgres password}
POSTGRES_DB={your postgres database name}
POSTGRES_URL=postgresql://{your postgres username}:{your postgres password}@{your postgres host name - this should be publicly accessible}:5432/{your postgres database name}?sslmode=disable
POSTGRES_SSL_ENABLED=false
DISABLE_POSTGRES_SSL=1
AUTH_TRUST_HOST=true

# ---- S3 / MinIO ----
MINIO_ROOT_USER={your minio root username}
MINIO_ROOT_PASSWORD={your root password}
MINIO_ACCESS_KEY={your minio username for this project}
MINIO_SECRET_ACCESS_KEY={your minio user password for this project}


NEXT_PUBLIC_MINIO_BUCKET={your minio bucket name}
NEXT_PUBLIC_MINIO_DOMAIN={your minio host name - this should be publicly accessible}
NEXT_PUBLIC_MINIO_PORT={your minio api port}

# Add other environment variables you want to use in this project below
# For some variables, you’ll need to rebuild the Docker image for the changes to take effect.
```
</details>

## Step 2: build the Docker image and launch it

First, launch the other services except this app.
```bash
sudo docker compose -f other-docker-compose.yaml up -d
```

Then, build the image - this process relies on your PostgreSQL, and it will take a while: 
```bash
sudo docker compose build exif-photo-blog
```

<details>
<summary>The build log for your reference, my settings might be different than yours</summary>

```
Compose now can delegate build to bake for better performances
Just set COMPOSE_BAKE=true
[+] Building 196.7s (20/20) FINISHED                                                                                                   docker:default
 => [exif-photo-blog internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 989B                                                                                                             0.0s
 => [exif-photo-blog internal] load metadata for docker.io/library/node:18-alpine                                                                0.6s
 => [exif-photo-blog internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [exif-photo-blog internal] load build context                                                                                               52.6s
 => => transferring context: 6.83MB                                                                                                             52.5s
 => [exif-photo-blog deps 1/5] FROM docker.io/library/node:18-alpine@sha256:8d6421d663b4c28fd3ebc498332f249011d118945588d0a35cb9bc4b8ca09d9e     0.0s
 => CACHED [exif-photo-blog deps 2/5] WORKDIR /app                                                                                               0.0s
 => CACHED [exif-photo-blog deps 3/5] RUN corepack enable                                                                                        0.0s
 => CACHED [exif-photo-blog deps 4/5] COPY package.json pnpm-lock.yaml ./                                                                        0.0s
 => CACHED [exif-photo-blog deps 5/5] RUN pnpm install --frozen-lockfile                                                                         0.0s
 => CACHED [exif-photo-blog builder 4/7] COPY --from=deps /app/node_modules ./node_modules                                                       0.0s
 => [exif-photo-blog builder 5/7] COPY . .                                                                                                      20.8s
 => [exif-photo-blog builder 6/7] RUN pnpm build                                                                                               104.3s
 => [exif-photo-blog builder 7/7] RUN ls -la .next && ls -la .next/static || true                                                                0.2s
 => CACHED [exif-photo-blog production 3/7] RUN corepack enable                                                                                  0.0s
 => CACHED [exif-photo-blog production 4/7] COPY package.json pnpm-lock.yaml ./                                                                  0.0s
 => CACHED [exif-photo-blog production 5/7] RUN pnpm install --prod --frozen-lockfile                                                            0.0s
 => [exif-photo-blog production 6/7] COPY --from=builder /app/.next ./.next                                                                      1.5s
 => [exif-photo-blog production 7/7] COPY --from=builder /app/public ./public                                                                    0.0s
 => [exif-photo-blog] exporting to image                                                                                                        12.4s
 => => exporting layers                                                                                                                         12.0s
 => => writing image sha256:e96b13aa2e3852366bd147ea2b17c1921016c96b402c62688e66f8aacdc1d882                                                     0.0s
 => => naming to docker.io/library/exif-photo-blog-exif-photo-blog                                                                               0.1s
 => [exif-photo-blog] resolving provenance for metadata file                                                                                     0.0s
[+] Building 1/1
 ✔ exif-photo-blog  Built
```
</details>

Finally launch this app
```bash
sudo docker compose up -d 
```


## Step 3 Set up MinIO

This section is adapted from the project’s README, with commands updated for the latest MinIO version.

1. Follow the [instructions](https://docs.min.io/community/minio-object-store/reference/minio-mc.html#quickstart) to install  MinIO client on your host machine or use the built-in mc within the docker container.
2. **Log in to the server**: use the command below to connect, and you can also find the WebUI at http://localhost:9001
    ```bash
    # MINIO_ROOT_USER and MINIO_ROOT_PASSWORD are what you set earlier in .env
    mc alias set myminio http://127.0.0.1:9000 {MINIO_ROOT_USER} {MINIO_ROOT_PASSWORD}
    # Added `myminio` successfully.
    ```
3. **Create the bucket**: Use the bucket name you set in the previous step    
    ```bash
    mc mb myminio/{BUCKET_NAME}
    # Bucket created successfully `myminio/photos`.
    ```
4. **Set public read policy**: Use the bucket name you set in the previous step - this is different from the project README due to the update of MinIO
    ```bash
    mc anonymous set public myminio/{BUCKET_NAME}
    # Access permission for `myminio/photos` is set to `public`
    ```
5. **Define user policy**: Create a file named `user-policy.json`. This policy will allow the user to list the bucket contents and to get, put, and delete objects within it. - Remember to change the bucket name.
    ```json
    {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:DeleteObject","s3:GetObject","s3:ListBucket","s3:PutObject"],"Resource":["arn:aws:s3:::{BUCKET_NAME}/*","arn:aws:s3:::{BUCKET_NAME}"]}]}
    ````
   
7. **Create policy**: Add a named policy to MinIO - this is also different due to MinIO update
    ```bash
    mc admin policy create myminio photos-manager-policy user-policy.json
    # Created policy `photos-manager-policy` successfully.
    ```
8. **Create user**: Create a new user with an access key and secret key.
    ```bash
    mc admin user add myminio {MINIO_ACCESS_KEY} {MINIO_SECRET_ACCESS_KEY}
    # Added user `{MINIO_ACCESS_KEY}` successfully.
    ```
9. **Attach policy to user**: Assign photos-manager-policy to the user.  - Again this is different due to MinIO update
    ```bash
    mc admin policy attach myminio photos-manager-policy --user {MINIO_ACCESS_KEY}
    # Attached Policies: [photos-manager-policy]
    # To User: {MINIO_ACCESS_KEY}
    ```

## Step 4 Then you are all set!
In the last several days, I learned a lot from other posts and interacting with GPT-5 and other language models. Huge thanks to all contributors—enjoy your self-hosted site! Again, I only have very limited knowledge in this domain, so please feel free to suggest any edits.

**Comment by Taosky** [comment]
> Thanks to everyone in this thread for sharing your solutions. After going through the previous posts and checking the latest codebase, I’ve put together a beginner-friendly guide that sums everything up. However, I have very limited knowledge in this domain, so please feel free to correct me.
> 
> ## Step 0 — What you’ll set up
> This guide spins up several Dockerized services required for the project and the project itself:
> 
> Service	Purpose	Default Port(s)	Direct User Access?
> MinIO	Object/image storage (S3-compatible)	9000 (API), 9001 (optional Console/WebUI)	Yes (API). Console optional.
> PostgreSQL	Image metadata database	5432 (local only)	Yes for your app and the machine to build the Docker image. No, for general users.
> coollabsio/next-image-transformation	Image optimization wrapper	8999	Yes
> imgproxy	Core image transformation engine	8080 (local only)	No (used behind the wrapper)
> This project (app)	Main web application	3000	Yes
> _**Important security note**_
> 
> > Several services will be reachable over the network. Do not use this configuration as-is for production. In my case, I use Nginx as a reverse proxy route by requested URLs to each container.
> 
> ## Step 1: Clone the project and create the following files in the root directory of the project.
> The following two edits are borrowed from [coollabsio/next-image-transformation](https://github.com/coollabsio/next-image-transformation)
> 
> Add the following lines to the end of next.config.ts
> Create a new file named loader.js, change imageOptimizationApi to your coollabsio/next-image-transformation container, and change baseUrl to your exif-photo-blog (this repo) container
> 'use client'
> 
> export default function myImageLoader({ src, width, quality }) {
>     const isLocal = !src.startsWith('http');
>     const query = new URLSearchParams();
> 
>     const imageOptimizationApi = '{change this to next-image-transformation container}';
>     // Your NextJS application URL
>     const baseUrl = '{change this to exif-photo-blog container}';
> 
>     const fullSrc = `${baseUrl}${src}`;
> 
>     if (width) query.set('width', width);
>     if (quality) query.set('quality', quality);
> 
>     if (isLocal && process.env.NODE_ENV === 'development') {
>         return src;
>     }
>     if (isLocal) {
>         return `${imageOptimizationApi}/image/${fullSrc}?${query.toString()}`;
>     }
>     return `${imageOptimizationApi}/image/${src}?${query.toString()}`;
> }
> Create Dockerfile - this code was generated by GPT5 and I'm not able to review it - please correct it if you found anything wrong
> other-docker-compose.yaml for all the containers except this repo. Edit where do you what to put images and the db - look for {edit me}
> docker-compose.yaml
> .env - Edit the environment variables here. For some variables, you’ll need to rebuild the Docker image for the changes to take effect.
> ## Step 2: build the Docker image and launch it
> First, launch the other services except this app.
> 
> sudo docker compose -f other-docker-compose.yaml up -d
> Then, build the image - this process relies on your PostgreSQL, and it will take a while:
> 
> sudo docker compose build exif-photo-blog
> The build log for your reference, my settings might be different than yours
> Finally launch this app
> 
> sudo docker compose up -d 
> ## Step 3 Set up MinIO
> This section is adapted from the project’s README, with commands updated for the latest MinIO version.
> 
> 1. Follow the [instructions](https://docs.min.io/community/minio-object-store/reference/minio-mc.html#quickstart) to install  MinIO client on your host machine or use the built-in mc within the docker container.
> 2. **Log in to the server**: use the command below to connect, and you can also find the WebUI at http://localhost:9001
>    # MINIO_ROOT_USER and MINIO_ROOT_PASSWORD are what you set earlier in .env
>    mc alias set myminio http://127.0.0.1:9000 {MINIO_ROOT_USER} {MINIO_ROOT_PASSWORD}
>    # Added `myminio` successfully.
> 3. **Create the bucket**: Use the bucket name you set in the previous step
>    mc mb myminio/{BUCKET_NAME}
>    # Bucket created successfully `myminio/photos`.
> 4. **Set public read policy**: Use the bucket name you set in the previous step - this is different from the project README due to the update of MinIO
>    mc anonymous set public myminio/{BUCKET_NAME}
>    # Access permission for `myminio/photos` is set to `public`
> 5. **Define user policy**: Create a file named `user-policy.json`. This policy will allow the user to list the bucket contents and to get, put, and delete objects within it. - Remember to change the bucket name.
>    {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:DeleteObject","s3:GetObject","s3:ListBucket","s3:PutObject"],"Resource":["arn:aws:s3:::{BUCKET_NAME}/*","arn:aws:s3:::{BUCKET_NAME}"]}]}
> 6. **Create policy**: Add a named policy to MinIO - this is also different due to MinIO update
>    mc admin policy create myminio photos-manager-policy user-policy.json
>    # Created policy `photos-manager-policy` successfully.
> 7. **Create user**: Create a new user with an access key and secret key.
>    mc admin user add myminio {MINIO_ACCESS_KEY} {MINIO_SECRET_ACCESS_KEY}
>    # Added user `{MINIO_ACCESS_KEY}` successfully.
> 8. **Attach policy to user**: Assign photos-manager-policy to the user.  - Again this is different due to MinIO update
>    mc admin policy attach myminio photos-manager-policy --user {MINIO_ACCESS_KEY}
>    # Attached Policies: [photos-manager-policy]
>    # To User: {MINIO_ACCESS_KEY}
> 
> ## Step 4 Then you are all set!
> In the last several days, I learned a lot from other posts and interacting with GPT-5 and other language models. Huge thanks to all contributors—enjoy your self-hosted site! Again, I only have very limited knowledge in this domain, so please feel free to suggest any edits.


Thanks to LostXine's tutorial, the deployment was successful. A few additional points:
1. The `url` in the `loader.js` file needs to include `https`; otherwise, requests may not work correctly.
2. Do not expose the `postgresql` port to the public network. Do not use `127.0.0.1` for the `POSTGRES_URL` in the `.env` file, as this will result in connection failures. I used a host address `10.x.x.x.x`
3. Comment out `NEXT_PUBLIC_MINIO_PORT` in the `.env` file (after reverse proxying, simply request the default web port).

--- 
感谢LostXine的教程，部署成功。补充几个点：
1. `loader.js`文件里面的`url`，需要加上https，否则可能无法正确请求
2. `postgresql`的端口不要暴露到外网，`.env`文件中`POSTGRES_URL`的地址不要使用`127.0.0.1`这种，会导致无法连接，我在使用的是主机10.开头的地址
3. `.env`文件中`NEXT_PUBLIC_MINIO_PORT`可以注释掉（反向代理后直接请求Web默认端口就行)
