### ISSUE TITLE
Option to: disable photo titles site-wide / hide "Untitled" text

### ISSUE THREAD

**Issue by vhogberg** [sambecker/exif-photo-blog#133]
Hello!
I'm bad at coming up with titles, and so 99% of my photos just say "Untitled" next to them, which looks a bit strange. 

So I was wondering if there was a possibility to: 
A. An option to remove the entire variable so titles are gone on all photos
B. An option to have no photo title per default as it is now, but have "Untitled" not show up, then for some photos where I'd like a title it would still be possible to enter one.

Thanks 🙂

**Comment by sambecker** [comment]
Just merged support for this via `NEXT_PUBLIC_HIDE_TITLE_FALLBACK_TEXT`

Please sync your fork and report any issues!

**Comment by vhogberg** [comment]
Synced now tested a bit and looks to be working perfectly! I appreciate it a lot, you're awesome 👊

**Comment by sambecker** [comment]
Of course @vhogberg so glad to hear it!
