### ISSUE TITLE
Likes button

### ISSUE THREAD

**Issue by ghenry** [sambecker/exif-photo-blog#140]
**Is your feature request related to a problem? Please describe.**
Like/Heart button

**Describe the solution you'd like**

We have analytics in Vercel, but would be great to have a Like/Heart button with number of likes, like Instagram. Only a pic when you click into it though.

Comments too, or too far?

**Comment by sambecker** [comment]
I've thought about this many times @ghenry and would love to support social features such as likes and comments but they would depend on a broader auth/account system and probably some for of moderation tools? Will definitely keep this in mind. I too would like to know what my most liked photos would be!

**Comment by ghenry** [comment]
Yeah, thinking more about it, brings a whole lot of extra attack surface area.
