### ISSUE TITLE
HDR Images

### ISSUE THREAD

**Issue by kunwarsahni01** [sambecker/exif-photo-blog#142]
Would be super cool to support HDR Images, probably would be not a super used feature, but thought to put the idea out there anyways 😅

**Comment by kunwarsahni01** [comment]
https://www.wide-gamut.com/test/image-hdr <- for taking a look at HDR images via the browser

**Comment by sambecker** [comment]
I, too, would like this @kunwarsahni01! And we strive for P3 support when [resizing images on the client](https://github.com/sambecker/exif-photo-blog/blob/76c02ee0156b9654850381cf7c67384448ed14d7/src/components/ImageInput.tsx#L107), but I believe full support would require changes to `next/image`.

Closing for now, but you can see this thread for details: https://github.com/vercel/next.js/discussions/52521
