### ISSUE TITLE
Project referral coupons?

### ISSUE THREAD

**Issue by ghenry** [sambecker/exif-photo-blog#143]
Hi Sam,

Just hit the limit to have to move on to a Pro plan on vercel.

Any special deals you have :-)

Thanks!

**Comment by sambecker** [comment]
I wish I could! What limitation are you bumping into?

**Comment by ghenry** [comment]
Shame! I thought you owned it.

Your site is growing!

Your free team ghenry1s-projects has used 75% of the included free tier
usage for Compute Time (60 hours).

PostgreSQL Compute Time weirdly.

**Comment by sambecker** [comment]
I wish!

Only cost savings I think of is trying out the [experimental Supabase support](https://github.com/sambecker/exif-photo-blog?tab=readme-ov-file#supabase).

Good luck!
