### ISSUE TITLE
Formatting for the about section

### ISSUE THREAD

**Issue by rnichaelt** [sambecker/exif-photo-blog#145]
It would be nice to be able to do some simple formatting in the about section, like bold or line breaks.

**Comment by sambecker** [comment]
I like that idea.

Basically, you could add the following tags to the text stored `NEXT_PUBLIC_SITE_ABOUT`?

[`<b>`, `<i>`, `<u>`, `<br />`]

**Comment by rnichaelt** [comment]
> I like that idea.
> 
> Basically, you could add the following tags to text stored in `NEXT_PUBLIC_SITE_ABOUT`?
> 
> [`<b>`, `<i>`, `<u>`, `<br />`]

Yes exactly! Thanks for all your work on this project

**Comment by sambecker** [comment]
Merged! Let me know if you have any issues using.
