### ISSUE TITLE
Saving filename

### ISSUE THREAD

**Issue by ignaciogiri** [sambecker/exif-photo-blog#150]
**Is your feature request related to a problem? Please describe.**
I've been looking for a tool like this one for a while. I was able to get it running in less than 2 hours. It's awesome.
But now when I tried to modify the app to also store the original filename of the upload file, I'm struggling.

**Describe the solution you'd like**
Sam - you did an amazing job documenting the app. Would you mind give us some guidance how could be add more fields we want to save? Or if something more complex such as extracting and saving all the IPTC core metadata as well.

**Comment by sambecker** [comment]
Hi @ignaciogiri!

> modify the app to also store the original filename of the upload file

I would look at function `convertUploadToPhoto` [defined here](https://github.com/sambecker/exif-photo-blog/blob/0c69efaab4922574632177131e51bb6fc3b91c44/src/photo/storage.ts#L22). When moving a temporary upload to its permanent location, this is where it gets named.

> add more fields we want to save

To do that, I would start by augmenting the `Photo` schema [here](https://github.com/sambecker/exif-photo-blog/blob/0c69efaab4922574632177131e51bb6fc3b91c44/src/photo/index.ts#L70), and creating a JIT migration [here](https://github.com/sambecker/exif-photo-blog/blob/0c69efaab4922574632177131e51bb6fc3b91c44/src/photo/db/query.ts#L62) (which would be modeled on something like `MIGRATION_FIELDS_01` + `runMigration01`).

Hopefully that's enough to get you started!

Thank you for your kind words.
