### ISSUE TITLE
Function to view Image in larger size

### ISSUE THREAD

**Issue by xingfanxia** [sambecker/exif-photo-blog#154]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Right now the user can only view a downsized preview of the actual image, is it possible to add a image viewer that is capable of zooming in and out?

**Comment by sambecker** [comment]
I would love this option—assume it would expand to full-screen, and offer left/right browsing within a set? Can you share an example of the zoom in/out behavior that like?

**Comment by xingfanxia** [comment]
@sambecker something along the line with this https://github.com/s-yadav/iv-viewer
