### ISSUE TITLE
Delete photo

### ISSUE THREAD

**Issue by ch3rr17** [sambecker/exif-photo-blog#158]
**Describe the bug**
I accidentally entered an invalid time value and now it doesn't show al the photos

**Does your template use custom code?**
No

**Steps to Reproduce**
1. Go to https://gallery.swichecaptures.com/grid. Nothing shows here
I deleted the photo in the blob, but it looks like it' still erroring out on the site.
2. Example url where you can a 500 error: https://gallery.swichecaptures.com/tag/favs

**Screenshots**
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/36c88ae1-e4d5-44b4-a41c-1c3f329c8192" />

**Device details**
 - Device/OS: Mac Sonoma 14.5
 - Browser:  Chrome
 - Version 130 (latest)

**Comment by ch3rr17** [comment]
I take that back. Cancelling request. I just deleted my photo via query

**Comment by sambecker** [comment]
Thanks for documenting @ch3rr17 did saving the incorrect date/time cause an issue, or was it only when you tried to delete a photo with an invalid date/time? And was part of the issue that a blob got deleted, but the photo database record persisted?
