### ISSUE TITLE
Vercel Blob hitting 100MB cap on outgoing bandwidth almost immediately

### ISSUE THREAD

**Issue by elibenton** [sambecker/exif-photo-blog#18]
Hey Sam! Thank you for making this website template. It is absolutely stunningly gorgeous, and I LOVE the simplicity of EXIF parsing. The whole thing is just so inspiring. I have one small question. While getting it set up, I've already hit the 100MB limit on Vercel Blob outgoing bandwidth twice! All of I've done is upload three or four photos, re-deploy a few times to get the environmental variables I want, and push a few tiny tweaks from a local copy. Is there anything I'm doing wrong, or is 100 MB just not enough bandwidth? I'd really hate to have to upgrade to Vercel Pro, $20 for a photo storage blob just feels wrong!

Thanks for any help you may be able to provide!

Eli

**Comment by elibenton** [comment]
Apologies, Sam, I’m seeing you already closed a similar comment. 

I think I’ll try to make a version that uses Cloudflare R2. That seems like it would be a good combo of beginner friendly but with a lot more bandwidth at a more reasonable price.

Would you be able to point me to all the spots in the code base where id need to make adjustments. Thanks!

**Comment by sambecker** [comment]
#21 adds support for [AWS S3](https://github.com/sambecker/exif-photo-blog#aws-s3)

Thank you for your kinds words @elibenton!

**Comment by elibenton** [comment]
Wow thank you so much!

**Comment by sambecker** [comment]
Of course! @elibenton let me know how it goes.
