### ISSUE TITLE
Control the direction of the photos

### ISSUE THREAD

**Issue by thjiang** [sambecker/exif-photo-blog#20]
Hello, after uploading the photos, some of them have been rotated 90° in direction. May I ask how to control the direction of photos?

Here is an example:
https://photos.thjiang.com/p/Kf4FK32A

**Comment by sambecker** [comment]
Very interesting. Have not encountered that issue yet. Can you post the original file so I can inspect?

**Comment by thjiang** [comment]
It seems that if the photo is taken vertically, the photo will be rotated.
Here are two examples of the original image.

https://pic.ziyuan.wang/2023/11/27/guest_291f3d6895336.JPG
https://pic.ziyuan.wang/2023/11/27/guest_9b8d8bf044350.JPG

**Comment by sambecker** [comment]
Just posted #22 to address this @thjiang—feedback welcome.

Will apply same thinking to `aspectRatio` before merging.

**Comment by sambecker** [comment]
Merged #22! Let me know if that worked @thjiang—will reopen if there are any other issues.

**Comment by thjiang** [comment]
Thank you very much for your prompt reply. I encountered some problems when deploying vercel so I couldn't verify it in time. I will check it as soon as possible after it is solved.

**Comment by sambecker** [comment]
> encountered some problems when deploying vercel

Build errors? Let me know if any seem specific to this update!

**Comment by thjiang** [comment]
> > encountered some problems when deploying vercel
> 
> Build errors? Let me know if any seem specific to this update!

It's my own problem with using Vercel, not caused by this project

**Comment by thjiang** [comment]
> Merged #22! Let me know if that worked @thjiang—will reopen if there are any other issues.

Many thanks for your help, it works perfectly now~

**Comment by sambecker** [comment]
Of course! So glad to hear.
