### ISSUE TITLE
?Next= URL Param Added to Homepage URL

### ISSUE THREAD

**Issue by mintmatica** [sambecker/exif-photo-blog#39]
Ever since moving to S3, my homepage is attempting to load the next set of images and progresses through a number of loops of which /"?Next={number}" is added to the end of the URL.

As the images are trying to load, the URL param number increments up to 115, then loads the next set of images.

In only have about 15 images loaded in S3 and my Vercel blob was deleted.

Any idea what could be causing this?

Thx,
Matt

![image](https://github.com/sambecker/exif-photo-blog/assets/96348408/dfbac096-779a-4e07-bf4a-a2030ce91823)

**Comment by sambecker** [comment]
I've seen this issue before when data falls out of sync.

Can you try clearing your cache from `/admin/configuration`?

![CleanShot 2024-01-09 at 20 44 56@2x](https://github.com/sambecker/exif-photo-blog/assets/169298/e6fa7805-4b4c-43e2-839e-265657adef5e)

**Comment by mintmatica** [comment]
that was it! ... thanks
