### ISSUE TITLE
500 error on login

### ISSUE THREAD

**Issue by mintmatica** [sambecker/exif-photo-blog#41]
Any idea why im getting a 500 server error when trying to log in?  All I did was add some SEO items and push to my main domain.

What super weird is that if I try to login on a vercel domain, everything works fine.  this url works:  https://pantaleone-bnn51uosa-my-team-98901580.vercel.app/admin

This URL does not and throws the errors:  https://pantaleone.net/admin

Pulling my hair out on this, but I have been using the vercel domain as my "admin domain"....

![Image 1-13-24 at 7 07 PM](https://github.com/sambecker/exif-photo-blog/assets/96348408/b73fd59e-3faf-4865-bf62-48d6f5f6aac2)

**Comment by sambecker** [comment]
What SEO items did you add?

Can you track down the actual error in Vercel logs?

**Comment by mintmatica** [comment]
im going to back out all my updates.  what's odd, is im getting the same exact thing if i try logging into your admin page.  I obviously dont have the login/pass, but this is exactly what im seeing.

Its like the callback URL cant be found for some reason....

Matt

![Image 1-14-24 at 11 30 AM](https://github.com/sambecker/exif-photo-blog/assets/96348408/94fd42db-7495-4d34-a265-7d1b3b574a81)

**Comment by sambecker** [comment]
Very interesting. I was able to log in and out my site just now without issue. However we did have a regression at some point where we stopped properly catching the auth error necessary to tell the user their login/password is wrong.

Can you verify that all auth environment variables are available in production? I believe there's 3, and a 4th meant only for development.

**Comment by mintmatica** [comment]
I dont think its due to incorrect login/pass.  When I enter the correct credentials, immediately, it throws the 500 error and white screen.  This did start occurring in the last couple of days.  Ill try to back out my changes in the meantime and see if that helps.

Here are all my current vercel environment variables:
[env variables pnet.pdf](https://github.com/sambecker/exif-photo-blog/files/13933326/env.variables.pnet.pdf)

**Comment by sambecker** [comment]
Try having your Vercel logs open when you try to sign in. You see a "credential" error at the time you see a 500.

Regarding the environment variables, is there a reason you have both `AUTH_SECRET` and `NEXT_AUTH_SECRET`?

**Comment by mintmatica** [comment]
added both, just to see if that could fix the issue.  Again, im not an experienced dev over here :).

**Comment by mintmatica** [comment]
I wonder if this is a DNS issue - Im able to log in via Vercel no problem to the same deployment thats on the vercel.app domain.  Super odd.

**Comment by sambecker** [comment]
Very interesting. That is possible. Are you sure the custom domain version works over HTTPS? And that it points to the same deployment as the vercel.app version?

**Comment by mintmatica** [comment]
correct, i just tested a couple times.  screenshot below.

When trying to login:

pantaleone.net - doesnt work
Second link (vercel) - works
Third link (vercel) - works

I did just change my DNS last night from Hostinger to Vercel.  will investigate more in the AM and report back.  

Matt

![image](https://github.com/sambecker/exif-photo-blog/assets/96348408/f16dc144-9c35-4e01-9e6e-8a3f7f6e02e5)

**Comment by sambecker** [comment]
OK—that leads me to lean toward it being DNS-related as well.

In the meantime, you might want to try syncing your fork. I posted a couple commits tonight that might help you debug.

**Comment by mintmatica** [comment]
This continues to be a super weird one.  Here are the various troubleshooting steps i've done without success.  As a reminder, my main domain - pantaleone.net - will not let me log into /admin.  I AM able to login on vercel.app domains.

Troubleshooting steps performed:
- Backed out all changes to the last working deployment - didnt work
- Deleted all historical DNS records on my domain registrar, keeping Vercel
- Reset the domains in Vercel - I removed pantaleone.net, then re-added the domain
- Reset the admin email and password
- Tried multiple devices and browsers with addons disabled.

Im going to try a couple more things with my old webhost, Hostinger to see if its on their side.

Let me know if you have any other thoughts, else, I'll report back.

Cheers,
Matt

![Image 1-16-24 at 7 15 PM](https://github.com/sambecker/exif-photo-blog/assets/96348408/e375fd25-341d-45c2-9919-fe8767a4aa33)

**Comment by sambecker** [comment]
What's the content for all four of those POST errors?

Can you for one you're using the last with code from `main`?

**Comment by mintmatica** [comment]
heres the second log:

![Image 1-16-24 at 7 53 PM](https://github.com/sambecker/exif-photo-blog/assets/96348408/42abdea3-4a40-4e51-b9ae-7c95f9b53bb9)


3rd:

![Image 1-16-24 at 7 55 PM](https://github.com/sambecker/exif-photo-blog/assets/96348408/704120ad-4f42-41c1-b371-235520eebdf7)


4th (I also pasted the full log below)

![Image 1-16-24 at 7 56 PM](https://github.com/sambecker/exif-photo-blog/assets/96348408/a129f78e-fd5a-43f2-ba0d-f88c6cd81262)

d: Read more at https://errors.authjs.dev#credentialssignin
    at Object.l (/var/task/.next/server/chunks/4692.js:6:101883)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c (/var/task/.next/server/chunks/4692.js:6:115329)
    at async c (/var/task/.next/server/chunks/4692.js:6:94922)
    at async s (/var/task/.next/server/chunks/4692.js:340:58128)
    at async i (/var/task/.next/server/chunks/5438.js:1:1953)
    at async /var/task/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
    at async rm (/var/task/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:5703)
    at async rD (/var/task/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:22546)
    at async J (/var/task/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25253) {
  type: 'CredentialsSignin',
  kind: 'signIn'
}

**Comment by mintmatica** [comment]
on your other ?'s:

Not using the latest code from main, thats the next step

If you diff your app from main does anything auth-related pop up? - Not sure, but all the logs appear to be auth related.

On DNS - I pointed everything to Vercel on Saturday except the name servers on accident.  I just pointed the name servers over.

![Image 1-16-24 at 8 06 PM](https://github.com/sambecker/exif-photo-blog/assets/96348408/c39b667c-4d33-48ea-a6af-ea79f16dd930)

**Comment by mintmatica** [comment]
oh, and on the 'www' non www - i just followed Vercels reco when adding a domain.  Im not directing traffic elsewhere.

**Comment by sambecker** [comment]
I see `CredentialsSignin` at the top of one of your logs which is most likely an email/password mismatch. If there's a safe way to do it, I would make sure your ENV vars match your email/password credentials. I wonder if it's a case of those environment variables landing in different domains linked to different environments? Might those differ in Production vs Preview?

**Comment by sambecker** [comment]
The latest auth code does a better job catching that particular error. Make sure you're running the latest auth code. If so, and there's a `CredentialsSignin` exception, you should no longer have a server crash but rather a red note that presented like this:

![CleanShot 2024-01-16 at 21 13 54@2x](https://github.com/sambecker/exif-photo-blog/assets/169298/96cdbfe3-3b1e-4c2c-ba69-a4aaf26d9ea1)

**Comment by sambecker** [comment]
You could also carefully add some server-side logging in `src/auth/index.ts` to make sure your email/password checks are comparing the right values:

![CleanShot 2024-01-16 at 22 13 58@2x](https://github.com/sambecker/exif-photo-blog/assets/169298/ce0efc2c-90d7-4da2-bfe2-999c2cb083e7)

**Comment by sambecker** [comment]
Closing for now. Let me know if you discover anything else that could help us debug.
