### ISSUE TITLE
Integration Request

### ISSUE THREAD

**Issue by XahidEx** [sambecker/exif-photo-blog#42]
I think It would be great if you also add `Cloudflare R2`. Aws, Vercel Blog & Cloudflare R2. ❤️

**Comment by sambecker** [comment]
This is something we'd like to support. It should be fairly straightforward to implement now that AWS has been integrated.

**Comment by sambecker** [comment]
Cloudflare R2 support has merged!

Please test it out and let me know if you run into any issues.

cc @XahidEx @narwhrl @elibenton
