### ISSUE TITLE
Handling non-EXIF data.....

### ISSUE THREAD

**Issue by tony-bologna** [sambecker/exif-photo-blog#43]
Great work on the template and architecture going on in your code! 
I've been wanting to show off some digital art on the photo blog. A lot of the digital  art that I have does not have EXIF data or its just plain irrelevant.
I know this basically contradicts how you've structured the way your code handles image data but assuming I am NOT navigating the EXIF data (which btw is very impressive how you reverse engineered it), is there a way in the ENV to turn off showing ALL EXIF data? Or will I have to basically re-engineer the website and delete the instances of exif data?

**Comment by tony-bologna** [comment]
The title, date, and tags are what I'd display yeah

**Comment by sambecker** [comment]
This can now be configured by setting `NEXT_PUBLIC_HIDE_EXIF_DATA = 1`
