### ISSUE TITLE
I got the error message while i try to clean cache 

### ISSUE THREAD

**Issue by cigar** [sambecker/exif-photo-blog#44]
Here is the error message while I navigate to this URL - /admin/configuration:

> Application error: a server-side exception has occurred (see the server logs for more information).
> Digest: 4223213064

And you can check more via this screen shot as below
![CleanShot 2024-01-18 at 16 16 31@2x](https://github.com/sambecker/exif-photo-blog/assets/389157/41e6b80d-cad3-4f73-8e58-2f37ef621811)

Thanks

**Comment by cigar** [comment]
Here is the second error message:
AccessDenied: Access Denied
    at throwDefaultError (/var/task/node_modules/.pnpm/@smithy+smithy-client@2.2.1/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /var/task/node_modules/.pnpm/@smithy+smithy-client@2.2.1/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_ListObjectsCommandError (/var/task/node_modules/.pnpm/@aws-sdk+client-s3@3.490.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4155:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/.pnpm/@smithy+middleware-serde@2.0.16/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/.pnpm/@aws-sdk+middleware-signing@3.489.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /var/task/node_modules/.pnpm/@smithy+middleware-retry@2.0.26/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
    at async /var/task/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.489.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
    at async /var/task/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.489.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at async /var/task/node_modules/.pnpm/@aws-sdk+middleware-logger@3.489.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'G3WER0AY6WGCXPTR',
    extendedRequestId: 'hR69riG1YoYWia3BhsBWLRzBSClPcmP4KYtyAeBVOKKP6IOOL4P7GzAwHRp/Q5I2/6++dqamjoAy2wBLL8l/eA==',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'AccessDenied',
  RequestId: 'G3WER0AY6WGCXPTR',
  HostId: 'hR69riG1YoYWia3BhsBWLRzBSClPcmP4KYtyAeBVOKKP6IOOL4P7GzAwHRp/Q5I2/6++dqamjoAy2wBLL8l/eA=='
}

**Comment by sambecker** [comment]
This looks like an AWS error. Has anything changed in your storage setup recently?

**Comment by sambecker** [comment]
Also, you may want to sync your fork. I've updated error handling a bit for both auth + storage.

**Comment by sambecker** [comment]
Going to close this for now. Let me know if you still have issues loading `/admin/configuration` after updating your fork/troubleshooting AWS.

**Comment by cigar** [comment]
I couldn't  loading /admin/configuration this address.

**Comment by sambecker** [comment]
Are you using AWS for storage, and have you updated your fork?

**Comment by sambecker** [comment]
Closing for now. Let me know if you keep running into this with the latest code/verified AWS configuration.
