### ISSUE TITLE
Is it possible to add multiple administrator accounts?

### ISSUE THREAD

**Issue by Lightingzahi** [sambecker/exif-photo-blog#45]
I have a few pals who would like to upload photos to this photo blog as well.

**Comment by sambecker** [comment]
Eventually, we may want a more sophisticated authentication system (possibly based on Github handles), which would allow for multiple admins, and possibly social features where verification/screening becomes important. Will keep this request in mind.

In the meantime, you can always adjust the code, which is basically an ENV VAR lookup to accommodate multiple pairs. This logic can be found here:
https://github.com/sambecker/exif-photo-blog/blob/main/src/auth/index.ts
