### ISSUE TITLE
SEO Enhancement

### ISSUE THREAD

**Issue by XahidEx** [sambecker/exif-photo-blog#49]
I think you could do something like keeping a unique meta title, and meta description for each photo. 
For example: `meta title = photo title` & `meta description` would be like `photo title | site name`.
It's for better SEO practices. Something you should consider. Now It all returns duplicate titles & descriptions

**Comment by sambecker** [comment]
This should be how the site works now. For instance, [this photo](https://photos.sambecker.com/p/Fl7XN7OS) includes the following meta:

![CleanShot 2024-01-23 at 22 43 18@2x](https://github.com/sambecker/exif-photo-blog/assets/169298/dd8b0315-eaf9-44a1-b8ec-45813a5a7083)

Might be fun to let users add more than just the title and date? Or include the name of the blog in the title, as you suggest. Will think on that.
