### ISSUE TITLE
I have requests - enable user to existing tags when we upload or edit a new photo

### ISSUE THREAD

**Issue by cigar** [sambecker/exif-photo-blog#50]
Hey Sam 

You did a fantastic job for update the exif photo repo, actually, I longing for a solution to share my photo like you design and developed, and after I tried it for two weeks, from my perspective, I found that i really want to select the existing tags when we upload upload a new photo,currently I can only do it just type the tag in every single time!

Therefore, there are a lot of tags on front page,

So, I suggest maybe we could add this feature for upload or editing page.

Thanks again!

**Comment by sambecker** [comment]
Thank you for those kind words @cigar.

Can you confirm what you're looking for is tag auto-complete when uploading or editing a photo? So it's easier to add an existing tag?

**Comment by cigar** [comment]
Let me clarify, for example, if we had added 2 tags(nature, portrait) for some of the photos last time.
and you can type a new tag or select the existing 2 tags; 
here is a reference for auto-complete from the AntDesign: 
https://ant.design/components/select
You can directly check the code via :https://sjkfvs.csb.app/

thanks you again!

**Comment by sambecker** [comment]
Makes total sense! Would love to have this functionality for tags. Will definitely consider it.

**Comment by sambecker** [comment]
Just merged this update! Let me know how it works.

**Comment by cigar** [comment]
It's so fantastic to have this feature! It worked on my side! I love this!
thanks you again
