### ISSUE TITLE
Could you provide a env to disable `blur_text` in SQL?

### ISSUE THREAD

**Issue by Aqours** [sambecker/exif-photo-blog#51]
https://github.com/sambecker/exif-photo-blog/blob/6e397b34feb17a0ae9682e015e60836971b446bf/src/services/vercel-postgres.ts#L29

## Reason
It looks like it takes up too much SQL space. (I use the vercel hobby plan)

## Solution
Provides a configuration(env) to disable the `blur_text` in SQL.

**alternative**: Create a placeholder image using CSS and `apect_ratio`, when the image is loading.

**Comment by sambecker** [comment]
Just merged!

You can try it out by setting `NEXT_PUBLIC_BLUR_DISABLED = 1`.

To remove historical blur data, you will need to either:
1. manually set `blur_data` to `null` in your database OR
2. delete existing images and re-upload them
