### ISSUE TITLE
When using R2, it is not possible to delete images

### ISSUE THREAD

**Issue by zzd** [sambecker/exif-photo-blog#57]
If storage is only using Cloudflare R2, then in the backend, you won't be able to delete images, and it will show a 500 error.

**Comment by sambecker** [comment]
Hi @zzd thanks for reaching out. Believe this may be due a glitch introduced in the ••• admin menu.

Can you sync your fork and try again?

**Comment by zzd** [comment]
It looks like it has been fixed, thank you!
