### ISSUE TITLE
Flickr Integration.

### ISSUE THREAD

**Issue by aramshiva** [sambecker/exif-photo-blog#61]
(feature request)
An env variable should be visible for a Flickr API Key. Where images are synced automatically using Flickr API.

**Comment by sambecker** [comment]
This is an interesting idea.

A few questions:
- How many images would you expect to sync?
- Would you expect all of them to sync, or just a subset?
- How often would you expect them to sync? Instantly? Once per night?
- Would you expect to be notified if syncing could not complete?

**Comment by sambecker** [comment]
Closing for now! Please reopen if you have thoughts on those questions.
