### ISSUE TITLE
The addition of Chinese tags is not supported.

### ISSUE THREAD

**Issue by zzd** [sambecker/exif-photo-blog#62]
Hello, Author.  the tag feature of the project is very practical, but I found that I cannot add Chinese tags, I can only add English.

**Comment by sambecker** [comment]
Thanks for reporting this @zzd 

Just pushed a tweak that makes tag text entry less restrictive

Can you sync your fork and let me know if it helps?

**Comment by zzd** [comment]
Thank you, I have resynchronized and redeployed. After testing, the issue has been fixed. Thank you!
