### ISSUE TITLE
auto add multiple photos

### ISSUE THREAD

**Issue by gurugeek** [sambecker/exif-photo-blog#64]
First of all thanks a lot of creating exif photo blog 👍 
I understand the value of adding a title to each photo and have a curated collection but I was wondering if there is an option that I am missing to auto add photos uploaded. If you upload e.g. 50 photos, going through one by one is not optimal. 

Of course these bulk uploads and adding to the gallery will be without title.

Is this option available? If not, how can it be added to save time in uploading multiple photos?
Thanks!

**Comment by sambecker** [comment]
Would love to build this though it requires changes to how photos are stored in the database. Biggest blocker is the way blur data is generated, which happens in the browser. Will definitely give it some thought.

**Comment by Geczy** [comment]
you could keep the person on the page as you process each photo 1 by 1, showing a progress / step counter

**Comment by sambecker** [comment]
Just merged this feature in #99 @gurugeek @Geczy hopefully this works for your use case
