### ISSUE TITLE
the content is centered?

### ISSUE THREAD

**Issue by Geczy** [sambecker/exif-photo-blog#65]
see pic, any idea?

![image](https://github.com/sambecker/exif-photo-blog/assets/1036968/4edb9a79-b21e-443e-bf37-1d6ee2b92652)

**Comment by sambecker** [comment]
This is deliberate. Layouts are meant to be left-aligned.

**Comment by Geczy** [comment]
But it's the same issue on the photos page, which isn't present on your homepage but is on mine. I haven't touched the code just created from vercel

**Comment by sambecker** [comment]
I'm confused. The image you shared is of the setup wizard/empty state, which looks correct.

If photos aren't displaying correctly, can you share an image of that?

**Comment by Geczy** [comment]
![image](https://github.com/sambecker/exif-photo-blog/assets/1036968/be950f70-c1c7-4309-be26-a278c80a42d3)

**Comment by sambecker** [comment]
That is the intended design.

This is what the demo app looks like in a wide browser:

![CleanShot 2024-03-03 at 22 05 26@2x](https://github.com/sambecker/exif-photo-blog/assets/169298/4ad33faf-9dcd-4307-a992-a3f9cfdbe3dd)
