### ISSUE TITLE
admin has scroll bars

### ISSUE THREAD

**Issue by Geczy** [sambecker/exif-photo-blog#66]
these should be hidden or set to overflow auto

![image](https://github.com/sambecker/exif-photo-blog/assets/1036968/98f8c362-e383-472f-b246-2f43c6a05f67)

**Comment by sambecker** [comment]
Which OS/browser are you seeing this in?

**Comment by Geczy** [comment]
PC and chrome. Mac auto hides scroll bars

**Comment by sambecker** [comment]
Do you see them anywhere outside the `/admin` section?

**Comment by Geczy** [comment]
I don't remember, I can check tonight when I get home again

**Comment by Geczy** [comment]
that page and the edit page 

![image](https://github.com/sambecker/exif-photo-blog/assets/1036968/4fb91179-1f4d-476c-8282-1602b625ac8e)

**Comment by sambecker** [comment]
Should be fixed with the latest updates to `main`. Sync your fork and let me know if you see any more scrollbars!
