### ISSUE TITLE
add a caption field

### ISSUE THREAD

**Issue by Geczy** [sambecker/exif-photo-blog#67]
would b great if we could include long text with a photo

![image](https://github.com/sambecker/exif-photo-blog/assets/1036968/345596c8-6a4b-4057-a9ba-c3352b1bf942)

**Comment by sambecker** [comment]
Would like to support this one day, though it would require slightly different responsive layouts.

**Comment by Geczy** [comment]
Wouldn't it just go under the title?

**Comment by sambecker** [comment]
Yeah, it's just that it would push content down, which will affect the 2, and 4 column layouts (as opposed to the desktop 1 column layout).  It's not a huge deal, but would definitely want to get it right.

**Comment by Geczy** [comment]
so should we leave the issue open until we get around to coding it?

**Comment by sambecker** [comment]
Think we can leave this one closed. Feature request has been noted. Not sure yet on prioritization + timing.

**Comment by sambecker** [comment]
Just added @Geczy sync your fork and give it a try! Up next: exploring AI automation.
