### ISSUE TITLE
Support non-AWS S3 endpoint

### ISSUE THREAD

**Issue by kylemclaren** [sambecker/exif-photo-blog#78]
This is for s3-compatible services like [Tigris](https://www.tigrisdata.com/docs/get-started/#3-start-building) or Wasabi — need to be able to specify an alternative endpoint.

Currently, the endpoint is inferred/constructed from the provided bucket name and region, but Tigris for instance requires this to be set to `fly.storage.tigris.dev` and Wasabi something like `s3.us-east-1.wasabisys.com`.

Adding support for this would allow explicitly setting an env variable of `AWS_S3_BASE_URL`, then if it's _not_ set in the environment, infer it: https://github.com/sambecker/exif-photo-blog/blob/main/src/services/storage/aws-s3.ts#L15-L17

I will take a crack at a PR for this...

**Comment by sambecker** [comment]
If you're planning to open a PR, please make sure the approach is backward compatible with existing installations.

I would think this could be added as an optional, explicit preference for AWS-compatible services, i.e., if the url exists, it will be preferred, otherwise we'll fall back to existing REGION/BUCKET syntax.

Have you confirmed this is the only modification required to support Tigris + Wasabi? If I remember correctly, Cloudflare's AWS-compatible integration required a bit more configuration.

**Comment by kylemclaren** [comment]
This is what I've tried:

```diff
diff --git a/src/services/storage/aws-s3.ts b/src/services/storage/aws-s3.ts
index ff93d725..70b22304 100644
--- a/src/services/storage/aws-s3.ts
+++ b/src/services/storage/aws-s3.ts
@@ -12,11 +12,12 @@ const AWS_S3_REGION = process.env.NEXT_PUBLIC_AWS_S3_REGION ?? '';
 const AWS_S3_ACCESS_KEY = process.env.AWS_S3_ACCESS_KEY ?? '';
 const AWS_S3_SECRET_ACCESS_KEY = process.env.AWS_S3_SECRET_ACCESS_KEY ?? '';
 
-export const AWS_S3_BASE_URL = AWS_S3_BUCKET && AWS_S3_REGION
+export const AWS_S3_BASE_URL = process.env.AWS_S3_BASE_URL || (AWS_S3_BUCKET && AWS_S3_REGION
   ? `https://${AWS_S3_BUCKET}.s3.${AWS_S3_REGION}.amazonaws.com`
-  : undefined;
+  : undefined);
 
 export const awsS3Client = () => new S3Client({
+  endpoint: AWS_S3_BASE_URL,
   region: AWS_S3_REGION,
   credentials: {
     accessKeyId: AWS_S3_ACCESS_KEY,
```

Quite a simple solution, not sure if it has the sort of backwards compatibility you had in mind? I don't _think_ it would break an existing installation because — until now — `AWS_S3_BASE_URL` is exported at runtime and not actually stored as a env variable?

>I would think this could be added as an optional, explicit preference
Are you thinking this should be configured with a different variable like `ALT_AWS_S3_BASE_URL` to avoid confusion?

> Have you confirmed this is the only modification required to support Tigris + Wasabi?
My change _does_ work as far as correctly setting the endpoint for the s3 SDK, however, I am hitting CORS issues with the Tigris bucket and not sure when I'll have bandwidth to figure that out.

**Comment by sambecker** [comment]
> Not sure if it has the sort of backwards compatibility you had in mind

Yeah, this looks like it would work for pre-existing installations. Would also need a parallel solution for [next.config.js](https://github.com/sambecker/exif-photo-blog/blob/main/next.config.js) which cannot import/share logic with the app.

> I am hitting CORS issues with the Tigris bucket

Yeah, it was issues like this that required an entirely different setup for Cloudflare. Would definitely want evidence that swapping the base url was sufficient to onboard new providers before offering this as an official configuration option.

**Comment by kylemclaren** [comment]
Cool, will open a draft PR and try figure out the CORS stuff...
