### ISSUE TITLE
Is there a way to bulk upload photos?

### ISSUE THREAD

**Issue by EmilianoGarciaLopez** [sambecker/exif-photo-blog#8]

**Comment by sambecker** [comment]
Not yet but I'd like to offer.

How many photos—and at what size—do you anticipate uploading at once?

**Comment by EmilianoGarciaLopez** [comment]
I was thinking of uploading around ~10 photos at once with each one being ~4 MB

**Comment by sambecker** [comment]
Just merged #14—feedback welcome!
