### ISSUE TITLE
Support AWS S3 compatible services

### ISSUE THREAD

**Issue by metgen** [sambecker/exif-photo-blog#82]
Hello, I would like to use your project with AWS S3 compatible object storage [,timeweb.cloud](https://timeweb.cloud/) Tell me how this can be implemented? I tried to edit this code but it didn't help
```javascript
export const AWS_S3_BASE_URL = AWS_S3_BUCKET
  ? `https://${AWS_S3_BUCKET}.s3.timeweb.cloud`
  : undefined;

``` 
![Снимок экрана от 2024-04-26 22-51-45](https://github.com/sambecker/exif-photo-blog/assets/41876289/34420f8f-620c-4ee3-95a4-eba6293fa529)

**Comment by sambecker** [comment]
This was discussed in #79 and was being prototyped by @kylemclaren in #78.

Key issues here seem to be related to CORS and, I would imagine, presigned urls.

There were some subtle differences between the AWS and Cloudflare implementations currently offered in the template so I wouldn't be surprised if each vendor is slightly different.

**Comment by metgen** [comment]
I tried to connect another s3 compatible storage, which is more flexibly configured, but it does not have the s3:PutObjectACL action. How much can this affect the work of a photo blog? And is it possible to somehow diagnose the connection using the API?

**Comment by metgen** [comment]
I tried to connect another s3 compatible storage, which is more flexibly configured, but it does not have the s3:PutObjectACL action. How much can this affect the work of a photo blog? And is it possible to somehow diagnose the connection using the API?

**Comment by sambecker** [comment]
Closing this in favor of #79 for now.
