### ISSUE TITLE
admin/photos route gets 404

### ISSUE THREAD

**Issue by huhuhang** [sambecker/exif-photo-blog#84]
After uploading a photo, clicking Create will redirect to the `admin/photos` route, displaying the 404 page shown below.

![20240428-08-20-13-EwJwYie7](https://github.com/sambecker/exif-photo-blog/assets/5147530/96cff983-9c22-4328-a2bb-b04b78392211)

Refreshing this page will restore it to normal.

The browser console did not see any specific error. 😂

**Comment by sambecker** [comment]
Can you visit the Vercel server logs when you get to that 404 page and see if there are any errors you can share?

**Comment by huhuhang** [comment]
@sambecker Hello, thank you for your reply. I just forked the latest changes of your repository, redeployed it, and the issue no longer exists. 😄

**Comment by sambecker** [comment]
So glad it worked out!
