### ISSUE TITLE
Admin-only photos by tag

### ISSUE THREAD

**Issue by kylemclaren** [sambecker/exif-photo-blog#93]
**Is your feature request related to a problem? Please describe.**
I would love to see an admin-only tag that can be added to a photo to make it viewable only by an admin. 

Not familiar enough with the auth patterns to understand if this is feasible, so wanted to kick off a conversation. 

**Describe the solution you'd like**
A special admin tag can be added to a photo to make it non-public.

**Comment by sambecker** [comment]
Right now you can add a photo and mark it as "hidden." Currently, these photos can't be viewed outside `/admin` but it's something we could enable.

Would making hidden photos accessible to logged in users address this use case?

Another consideration is that these photos are hidden via obscurity. Technically, any raw image uploads could be accessed directly from the storage provider if you know the random url.

**Comment by kylemclaren** [comment]
> Would making hidden photos accessible to logged in users address this use case?

Yes!

> Technically, any raw image uploads could be accessed directly from the storage provider if you know the random url.

True. Google Drive basically employs this strategy. But I'd like to have these pics behind auth and prevent any possibility they'll be crawled.

**Comment by sambecker** [comment]
Just merged a small update to hidden photo accessibility—hopefully this is a good first step, with sufficient safeguards. Closing for now. Feedback welcome.

**Comment by kylemclaren** [comment]
Thanks for the work here @sambecker and sorry for the delay testing it! Trying to run `next build` and getting this error:
```
Error occurred prerendering page "/tag/hidden". Read more: https://nextjs.org/docs/messages/prerender-error
> Export encountered errors on following paths:
        /tag/hidden/page: /tag/hidden
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by sambecker** [comment]
> Export encountered errors ...

Does it say anywhere what the errors are?

Are you seeing this locally or when deploying? Does your fork have any code changes?

**Comment by sambecker** [comment]
Just pushed a small update, which might help `/tag/hidden` build

**Comment by kylemclaren** [comment]
Thanks for figuring that out — worked a charm ✨

**Comment by kylemclaren** [comment]
> these photos can't be viewed outside /admin but it's something we could enable.

@sambecker sorry, seems I slightly misunderstood your implementation initially. In testing this, I think these photos would probably need to be accessible outside of `/admin` for this feature to be useful?

So to clarify, an admin (logged in user) should be able to browse a collection of hidden and non-hidden photos in full frame and grid views — while an unauthenticated users should only see un-hidden pics.

**Comment by sambecker** [comment]
This is definitely possible but would prevent static generation of core template views. It's conceivable we could let people opt into that behavior if they're fine with the reduced performance/function cold starts.
